[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.8" }
pollster = { version = "0.4" }
wgpu = { version = "24.0.1" }
hecs = "0.10.5"
bytemuck = { version = "1.13", features = ["derive"] }